language: node_js
node_js: node

cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli

install: npm install

before_script:
  - npm install -g gulp

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - git config user.name "WhiteAce"
  - git config user.email "whiteace@yeah.net"
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - cat ./_config.yml
  - hexo deploy

branches:
  only:
    - gh-pages 
